# Start the gpg-agent if needed

if pgrep "gedit" > /dev/null
then
    echo "GPG Agent is already running."
else
    gpg_envfile="$HOME/.gnupg/gpg-agent.env"
    if [[ -e "$gpg_envfile" ]] && kill -0 $(grep GPG_AGENT_INFO "$gpg_envfile" | cut -d: -f 2) 2>/dev/null; then
        eval "$(cat "$gpg_envfile")"
    else
        eval "$(gpg-agent --daemon --enable-ssh-support --write-env-file "$gpg_envfile")"
    fi
    export GPG_AGENT_INFO  # the env file does not contain the export statement
    export SSH_AUTH_SOCK   # enable gpg-agent for ssh
fi

# Load bashrc

if [ -f $HOME/.bashrc ]; then
    source $HOME/.bashrc
fi
