# Env vars
export PATH=$PATH:/opt/local/bin:/opt/local/sbin:~/bin:~/work/bin:~/.rvm/bin
export EDITOR=emacs

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Don't put duplicate lines in the history.
HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}ignoredups
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoreboth

# Append to the history file, don't overwrite it
shopt -s histappend

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        color_prompt=yes
    else
        color_prompt=
    fi
fi

# Enable programmable completion features
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Prompt
if [ $(id -u) -eq 0 ];
then
    PS1="\e[0;31m[\A] \u@\h \w # \e[m"
else
    PS1="[\A] \e[0;34m\u@\h\e[0m \w $ "
fi

# Set term title
function termtitle {
  if [ -z $1 ]; then
    title=$USER"@"`hostname`
  else
    title=$1
  fi

  echo -n -e "\033]0;"$title"\007"
}

termtitle

# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
fi

# Aliases (a.k.a evil)
arch=`uname`
if [ $arch = "Darwin" ]; then
    export CLICOLOR=1
    export LSCOLORS=GxFxCxDxBxegedabagaced
    alias l="ls -lh"
    alias la="ls -lhA"
    alias xemacs='/Applications/Emacs.app/Contents/MacOS/Emacs -g 321x84+0+70 &'
    alias gnus='/Applications/Emacs.app/Contents/MacOS/Emacs -g 321x84+0+70 -f gnus &'
elif [ $arch = "Linux" ]; then
    alias l="ls -lh --color=auto"
    alias la="ls -lhA --color=auto"
    alias gnus='env DBUS_SESSION_BUS_ADDRESS="autolaunch:" emacs -f gnus &'
fi

alias grep='grep --color=auto'
alias rcl='find . -name "*~" -exec rm -f {} \; ; find . -name ".*~" -exec rm -f {} \; ; find . -name "._*" -exec rm -f {} \; ; find . -name ".DS*" -exec rm -f {} \;'
alias modified='find . | while read FILE;do ls -dl "$FILE";done | grep `date +"%b"` | grep `date +"%_d"`'
alias etagsup='rm -f TAGS; find . -regex ".*\.\(c\|cpp\|go\|h\|rb\|py\|php\)" -print | xargs etags -a'
alias en='emacs -nw'
alias enq='emacs -nw -Q'
alias irb='irb --simple-prompt'
alias curl='curl --progress-bar'
