#
# When on OpenBSD, add ". ~/.kshrc" in ~/.profile
# 

export PKG_PATH=ftp://ftp.fr.openbsd.org/pub/OpenBSD/`uname -r`/packages/`machine -a`/

 PS1="\n\u@\H\n\w \\$ "

alias l='ls -l'
alias la='ls -la'
alias rcl='find . -name "*~" -exec rm -f {} \; ; find . -name ".*~" -exec rm -f {} \;'
alias irb='irb --simple-prompt'
alias curl='curl --progress-bar'
